### ISSUE TITLE
I can open the project file in unity,but the window of hierarchy can't show anything of the scenes.

### ISSUE THREAD

**Issue by Cloud-OG** [Stefaaan06/aeterna#6]
I guess it's because my editor don't have installed the same packages as the project.But I don't know how to solve the problem.

**Comment by Stefaaan06** [comment]
Sorry for the late response -

Which unity version are you using? Are you getting any errors?
It could help if you posted a screenshot of the result youre getting

**Comment by Cloud-OG** [comment]
Oh, I finally succeeded in cloning it, it just works!
But clicking to download doesn't work.

**Comment by Stefaaan06** [comment]
What do you mean by "clicking to download doesn't work"?

**Comment by Cloud-OG** [comment]
![image](https://github.com/user-attachments/assets/3be3417a-5d28-4b1e-97af-68fe22071409)
Just like this. This way to get the project file is different from git clone.

**Comment by Cloud-OG** [comment]
And my editor version is unity6000.0.23f1

**Comment by Stefaaan06** [comment]
hmm thats weird - it should give you the same results as cloning the projekt
